import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { autoIsDarkOrLight } from "@/utils/time-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dreams luoan Activation",
  description: "Generated by Activation",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = autoIsDarkOrLight();
  console.log(theme);
  return (
    <html lang="en" data-theme={theme}>
      <body className={inter.className}>
        {children}
        {/*<Theme>{children}</Theme>*/}
      </body>
    </html>
  );
}
